apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gestor-clientes
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: southamerica-east1-docker.pkg.dev/PROJECT_ID/prestige-club-repo/gestor-clientes:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Configuraci贸n de base de datos
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://DB_HOST:5432/DB_NAME"
        - name: SPRING_DATASOURCE_USERNAME
          value: "DB_USER"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        
        # Configuraci贸n de JWT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        
        # Configuraci贸n de email
        - name: SPRING_MAIL_HOST
          value: "smtp.gmail.com"
        - name: SPRING_MAIL_PORT
          value: "587"
        - name: SPRING_MAIL_USERNAME
          value: "your-email@gmail.com"
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-password
              key: password
        
        # Configuraci贸n del servidor
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
